### ISSUE TITLE
PARSER3.0 - Pole FT

### ISSUE THREAD

**Issue by demoniaccz** [emaniac/parser#1]
Pokud chci vytvorit output z nekolika adresaru za sebou, tak se retezi cisla v poli FT. 

priklad: prvni adresar se jmenuje 666 a druhy 999. Pokud tedz nevypnu aplikaci a pokracuji vytvarenim outputu z druheho adresare, tak dostanu ve vysledku hodnotu ve FT 999666. 

cil: Ve FT by melo byt vzdy pouze jmeno soucasneho adresare.

P.S. mozna by jednoduse stacilo aby po vytvoreni prvniho outputu resetovat do defaultniho nastaveni

**Comment by emaniac** [comment]
Solved in 3.1
